### ISSUE TITLE
[1.1.0] mw.data.representation: TurtleParser-&gt;deserialize(): Turtle-Serializer: Failed to parse

### ISSUE THREAD

**Issue by cstockloew** [universAAL/middleware#139]
_Originally Opened: Oliver Strnad (2012-05-21 13:02:38_)
_Originally Closed: 2013-10-31 13:21:28_

Context: Whenever I try to retrieve an instance of an ontology class from the CHE which does not exist I get the following exception:

[Felix Shell TUI] ERROR org.universAAL.mw.data.serialization - TurtleParser-&gt;deserialize(): Turtle-Serializer: Failed to parse returning null!
java.lang.NullPointerException
at org.universAAL.serialization.turtle.TurtleParser.deserialize(TurtleParser.java:163)
at org.universAAL.serialization.turtle.TurtleParser.deserialize(TurtleParser.java:154)
at org.universAAL.context.space.osgi.ApplicationEntryServices.getApplicationEntry(ApplicationEntryServices.java:32)
at org.universAAL.context.space.osgi.Activator.start(Activator.java:94)
at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:639)
at org.apache.felix.framework.Felix.activateBundle(Felix.java:1700)
at org.apache.felix.framework.Felix.startBundle(Felix.java:1622)
at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:915)
at org.apache.felix.shell.impl.StartCommandImpl.execute(StartCommandImpl.java:114)
at org.apache.felix.shell.impl.Activator$ShellServiceImpl.executeCommand(Activator.java:286)
at org.apache.felix.shell.tui.Activator$ShellTuiRunnable.run(Activator.java:184)
at java.lang.Thread.run(Thread.java:662)

This happens when I have an empty output from the CHE like this:

[Thread-20] INFO org.universAAL.ctxt.space - ServiceCaller-&gt;handleReply(): 1376ecbd54f@HORNISSE+6efcd7f9_5 received service response:

@prefix ns: &lt;http://ontology.universAAL.org/SpaceServer.owl#&gt; .
@prefix ns1: &lt;http://www.daml.org/services/owl-s/1.1/Process.owl#&gt; .
@prefix : &lt;http://ontology.universAAL.org/uAAL.owl#&gt; .
_:BN000000 a :ServiceResponse ;
  :callStatus :call_succeeded ;
  :returns (
    ns:outputFromCHE
  ) .
ns:outputFromCHE ns1:parameterValue &quot;&quot;^^&lt;http://www.w3.org/2001/XMLSchema#string&gt; ;
  a ns1:Output .
:call_succeeded a :CallStatus .

I propose the following workaround: It is no problem for the caller of TurtleParser-&gt;deserialize() to check whether the method returned null. The exception is thrown at 

[..]
if (wasXMLLiteral)
  result = result.copyAsXMLLiteral();
  else if (Resource.TYPE_RDF_LIST.equals(result.getType())) {
[..]

I guess its the result.getType() which throws because result == null. So after assigning result at Resource result = finalizeAndGetRoot(); result should be checked for null. If it is null, null should be returned. Otherwise the program flow can continue as already implemented.

Best regards,
Oliver

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by cstockloew** [comment]
_Original author: @Alfiva (2012-05-21 18:02:17)_

Regardless of what can be done to the serializer, I have one customer-satisfaction question: Do you think it would be better that CHE returned an Error response instead of empty string, whenever this happens?

**Comment by cstockloew** [comment]
_Original author: Oliver Strnad (2012-05-22 08:36:34)_

Perhaps it would be good to have &quot;Service-specific failure&quot; as the call status instead of &quot;Call succeeded&quot;. But then the CHE service would need something like a &quot;get last error&quot;-method to provide additional information. I don't think it would be good to force the user to make another &quot;type check&quot; on the Resource returned by the service, just to see whether it is an instance of e.g. &quot;CHEError&quot;. This would increase complexity for the developers and is not something developers will easily get used to.

So I would vote for a &quot;Service-specific failure&quot; -&gt; &quot;get last error&quot;-method solution, since this is something developers know.

**Comment by cstockloew** [comment]
_Original author: Oliver Strnad (2012-05-22 08:39:39)_

But independently from the discussion above: the mentioned patch should be applied since the problem is something other services developed by 3rd-party developers could suffer from. Either check for null and return null if true, or throw an adequate exception, because the NullPointerException is very misleading here, since the problem (it actually is no real problem imho) is something else.

**Comment by cstockloew** [comment]
_Original author: @cstockloew (2013-10-31 13:21:28)_

does not occur anymore after the latest bug fixes in 2.0.3-SNAPSHOT

**Comment by cstockloew** [comment]
issue cloed on 2013-10-31 13:21:28
