### ISSUE TITLE
exception during shutdown

### ISSUE THREAD

**Issue by cstockloew** [universAAL/middleware#20]
_Originally Opened: Peter Wolf (2011-04-15 15:52:49_)
_Originally Closed: 2012-02-07 22:44:38_

I get the following exception when I type shutdown. This happens, for example, with the lighting-example configuration. But I assume it happens in any configuration. I don't know whether this is the right groups for this kind of bug, though.

-&gt; ERROR: EventDispatcher: Error during dispatch. (java.lang.IllegalStateException: Invalid BundleContext.)
java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:393)
	at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:316)
	at org.universAAL.middleware.sodapop.impl.SodaPopImpl.serviceChanged(SodaPopImpl.java:129)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:765)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:623)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:554)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:3566)
	at org.apache.felix.framework.Felix.access$200(Felix.java:37)
	at org.apache.felix.framework.Felix$2.serviceChanged(Felix.java:833)
	at org.apache.felix.framework.ServiceRegistry.fireServiceChanged(ServiceRegistry.java:559)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:96)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:118)
	at org.apache.felix.framework.ServiceRegistry.unregisterServices(ServiceRegistry.java:135)
	at org.apache.felix.framework.Felix._stopBundle(Felix.java:2068)
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2004)
	at org.apache.felix.framework.Felix.setFrameworkStartLevel(Felix.java:1188)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:265)
	at java.lang.Thread.run(Unknown Source)
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.configmanager.internal.Activator] : Stopping [org.ops4j.pax.configmanager]
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling SLF4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Jakarta Commons Logging API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Log4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Avalon Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling JULI Logger API support.

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by cstockloew** [comment]
_Original author: @amedranogil (2011-06-22 15:31:26)_

Yes this happens with any configuration.
some Activator doesn't manage BundleContext correctly.
...
15:14:29.155 - DEBUG - [FelixStartLevel]  mw.data.serialization - ServiceEvent UNREGISTERING
15:14:29.156 - DEBUG - [FelixDispatchQueue]  mw.data.serialization - BundleEvent STOPPED
15:14:29.159 - DEBUG - [FelixStartLevel]  mw.data.representation - ServiceEvent UNREGISTERING
15:14:29.162 - DEBUG - [FelixStartLevel]  mw.data.representation - ServiceEvent UNREGISTERING
15:14:29.163 - DEBUG - [FelixDispatchQueue]  mw.data.representation - BundleEvent STOPPED
ERROR: EventDispatcher: Error during dispatch. (java.lang.IllegalStateException: Invalid BundleContext.)
java.lang.IllegalStateException: Invalid BundleContext.
        at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:393)
        at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:316)
        at org.universAAL.middleware.sodapop.impl.SodaPopImpl.serviceChanged(SodaPopImpl.java:131)
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:820)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:678)
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:609)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:3640)
        at org.apache.felix.framework.Felix.access$200(Felix.java:38)
        at org.apache.felix.framework.Felix$2.serviceChanged(Felix.java:841)
        at org.apache.felix.framework.ServiceRegistry.fireServiceChanged(ServiceRegistry.java:568)
        at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:105)
        at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:118)
        at org.apache.felix.framework.ServiceRegistry.unregisterServices(ServiceRegistry.java:144)
        at org.apache.felix.framework.Felix._stopBundle(Felix.java:2105)
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2034)
        at org.apache.felix.framework.Felix.setFrameworkStartLevel(Felix.java:1197)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:265)
        at java.lang.Thread.run(Thread.java:662)
15:14:29.165 - DEBUG - [FelixStartLevel]  mw.bus.model - ServiceEvent UNREGISTERING
15:14:29.166 - DEBUG - [FelixDispatchQueue]  mw.bus.model - BundleEvent STOPPED
15:14:29.167 - DEBUG - [FelixStartLevel]  mw.acl.upnp - ServiceEvent UNREGISTERING
...

**Comment by cstockloew** [comment]
_Original author: @amedranogil (2011-07-14 13:35:56)_

I managed to solve this locally. 
Apply the atached patch to the following class:
org.universAAL.middleware.sodapop.impl.SodaPopImpl

it just nullifies the context reference when the stop method is called, and adds a check &quot;if&quot; in serviceChanged method

**Comment by cstockloew** [comment]
issue cloed on 2012-02-07 22:44:38
