### ISSUE TITLE
Error while trying to lauch 1.2.1-SNAPSHOT mw after release

### ISSUE THREAD

**Issue by cstockloew** [universAAL/middleware#253]
_Originally Opened: @amedranogil (2012-11-29 13:18:28_)
_Originally Closed: 2013-03-25 20:24:49_

got this exception while trying to start the bus model bundle:

13:14:59.887 - DEBUG - [FelixDispatchQueue]  mw.bus.model.osgi - BundleEvent STOPPED
org.osgi.framework.BundleException: Activator start error in bundle mw.bus.model.osgi [15].
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2027)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1895)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:944)
	at org.apache.felix.gogo.command.Basic.start(Basic.java:729)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
	at org.apache.felix.gogo.shell.Console.run(Console.java:62)
	at org.apache.felix.gogo.shell.Shell.console(Shell.java:203)
	at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
	at org.apache.felix.gogo.shell.Activator.run(Activator.java:75)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.SecurityException: CryptUtil already initialized
	at org.universAAL.middleware.sodapop.impl.CryptUtil.init(CryptUtil.java:165)
	at org.universAAL.middleware.sodapop.impl.SodaPopImpl.&lt;init&gt;(SodaPopImpl.java:135)
	at org.universAAL.middleware.sodapop.impl.osgi.Activator.start(Activator.java:52)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:641)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1977)
	... 32 more
java.lang.SecurityException: CryptUtil already initialized

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by cstockloew** [comment]
_Original author: @cstockloew (2012-11-30 07:17:39)_

I did not get this error, but I got a different error that may have the same origin (I got an error in acl.upnp). Yor error means that CryptUtil is called twice, and it is only called from the Activator, so this should not happen.

This error probably needs some more investigation, but I could 'solve' it by not using composites in my run config. The problem, in my case, was the pax runner which does not properly handle the ordering of bundles with composites. It is random (I think pax internally uses a hashtable somewhere and just enumerates the elements of that table, so the ordering of bundles somehow depends on the hashfunction...).

Maybe the new pax runner replacement from WP3 could also solve it. What do you use? Do you have composites? Do you use the original pax runner? If so, can you try it without composites?

Since the order in which the bundles are started is important for such an error, you could also check the run levels of bundles in your run config, but I assume you did not change anything when this error only occured directly after the release..

**Comment by cstockloew** [comment]
_Original author: @amedranogil (2012-11-30 12:23:48)_

yes I used composites, nevertheless I also 'solved' it by commenting the CryptUtil Call in the bus.model.core component.

I think This will be solved if the calls to the CryptUtil check first if it is initialized, or capture this exception.

**Comment by cstockloew** [comment]
_Original author: @cstockloew (2013-03-25 20:24:49)_

no longer existent in middleware 2

**Comment by cstockloew** [comment]
issue cloed on 2013-03-25 20:24:49
