### ISSUE TITLE
When restarting MW2.0 Modules are trying to perform bus communications before the busses are up

### ISSUE THREAD

**Issue by cstockloew** [universAAL/middleware#292]
_Originally Opened: @amedranogil (2013-04-17 11:20:33_)
_Originally Closed: 2015-01-30 13:58:29_

The bus implementations need to be sinchronized in MW2.0.

see this trace:

karaf@uAAL&gt;Exception in thread &quot;Thread-13&quot; java.lang.ExceptionInInitializerError
        at org.universAAL.context.prof.serv.SCallee.&lt;init&gt;(SCallee.java:100)
        at org.universAAL.context.prof.serv.Hub.start(Hub.java:67)
        at org.universAAL.context.prof.serv.osgi.Activator$1.run(Activator.java:82)
Caused by: java.lang.RuntimeException: Class not registered: http://ontology.universAAL.org/Profile.owl#ProfilingService
        at org.universAAL.middleware.owl.ManagedIndividual.init(ManagedIndividual.java:121)
        at org.universAAL.middleware.owl.ManagedIndividual.&lt;init&gt;(ManagedIndividual.java:94)
        at org.universAAL.middleware.service.owl.Service.&lt;init&gt;(Service.java:160)
        at org.universAAL.ontology.profile.service.ProfilingService.&lt;init&gt;(ProfilingService.java:46)
        at org.universAAL.context.prof.serv.SCalleeProvidedService.&lt;clinit&gt;(SCalleeProvidedService.java:118)
        ... 3 more

karaf@uAAL&gt;
karaf@uAAL&gt;Exception in thread &quot;Thread-25&quot; java.lang.RuntimeException: Class not registered: http://ontology.universAAL.org/PhysicalWorld.owl#Location
Exception in thread &quot;Thread-14&quot;         at org.universAAL.middleware.owl.ManagedIndividual.init(ManagedIndividual.java:121)
        at org.universAAL.middleware.owl.ManagedIndividual.&lt;init&gt;(ManagedIndividual.java:94)
        at org.universAAL.middleware.owl.ComparableIndividual.&lt;init&gt;(ComparableIndividual.java:50)
        at org.universAAL.middleware.owl.supply.AbsLocation.&lt;init&gt;(AbsLocation.java:62)
        at org.universAAL.ontology.location.Location.&lt;init&gt;(Location.java:75)
        at org.universAAL.ui.handler.gui.swing.Renderer.getRendererLocation(Renderer.java:502)
        at org.universAAL.ui.handler.gui.swing.Handler.&lt;init&gt;(Handler.java:75)
        at org.universAAL.ui.handler.gui.swing.Renderer.&lt;init&gt;(Renderer.java:176)
        at org.universAAL.ui.handler.gui.swing.Renderer.&lt;init&gt;(Renderer.java:204)
        at org.universAAL.ui.handler.gui.swing.Renderer$RenderStarter.run(Renderer.java:559)
        at java.lang.Thread.run(Thread.java:662)
java.lang.NullPointerException
        at org.universAAL.middleware.ui.impl.UIBusImpl.getUIBusFetchParams(UIBusImpl.java:59)
        at org.universAAL.middleware.ui.UICaller.&lt;init&gt;(UICaller.java:54)
        at org.universAAL.ui.dm.DialogManagerImpl.&lt;init&gt;(DialogManagerImpl.java:119)
        at org.universAAL.ui.dm.DialogManagerImpl.createInstance(DialogManagerImpl.java:314)
        at org.universAAL.ui.dm.osgi.DialogManagerActivator.run(DialogManagerActivator.java:36)

karaf@uAAL&gt;
-------------------------------------------------------------------
GMS: address=e9a792fe-9f21-4e0e-b5d1-4f0ddd30d1e3, cluster=mw.modules.aalspace.osgi, physical address=192.168.1.185:53610
-------------------------------------------------------------------

-------------------------------------------------------------------
GMS: address=e9a792fe-9f21-4e0e-b5d1-4f0ddd30d1e3, cluster=mw.bus.ui.osgi, physical address=192.168.1.185:53613
-------------------------------------------------------------------

-------------------------------------------------------------------
GMS: address=e9a792fe-9f21-4e0e-b5d1-4f0ddd30d1e3, cluster=mw.brokers.control.osgi, physical address=192.168.1.185:53615
-------------------------------------------------------------------

-------------------------------------------------------------------
GMS: address=e9a792fe-9f21-4e0e-b5d1-4f0ddd30d1e3, cluster=mw.bus.context.osgi, physical address=192.168.1.185:53618
-------------------------------------------------------------------

-------------------------------------------------------------------
GMS: address=e9a792fe-9f21-4e0e-b5d1-4f0ddd30d1e3, cluster=mw.bus.service.osgi, physical address=192.168.1.185:53621
-------------------------------------------------------------------

First 2 exceptions are due to first the prof server trying to call through the service bus and second the swing handler trying to perform some operations on the UI (the actual exception is because there is also an error on ontologies starting when restarting in karaf); BOTH BEFORE THE BUSSES ARE CREATED!!!

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by cstockloew** [comment]
_Original author: @cstockloew (2013-04-23 18:02:16)_

The exceptions come from profiling Server and Dialog Manager being started before the ontologies (i.e. Physical world ontology and Profiling ontology). Please check the run levels of these components in your run config. The exceptions are not related to communication of the busses at network level.

The problem of components starting before the communication connector is configured happened for me only for non-space-coordinator nodes (peerRole=PEER). Does this happen on your pc on a space-coordinator node or a non-space-coordinator node? For space-coordinator nodes (peerRole=COORDINATOR) the space (and also the communication connector) is set up synchronously and blocks; when the connector is set up (then you see the &quot;GMS: ..&quot; lines), then the other bundles are started.

However, for non-space-coordinator nodes (peerRole=PEER), the configuration is done asynchronously in a separate thread and the configuration is done as soon as it is received through the SLP discovery from the space-coordinator node. This has been a problem because messages that are sent on a channel that was not configured were thrown away. In rev2669 this behaviour was changed so that the busses (i.e. AbstractBus) will wait (and block) until the communication connector is configured correctly and you may see the following message:

&quot;The communication connector is not yet configured correctly (channel xx is unknown). Waiting for the configuration to send the message. Time elapsed: yy&quot;

So, there can be some message from components in the log before the &quot;GMS: ..&quot; lines but the messages are not sent before the communication is established.

This behaviour could be changed to a non-blocking way by using a buffer, but it should not cause an error. Please check if there is an error (e.g. a missing message).

**Comment by cstockloew** [comment]
_Original author: @Alfiva (2015-01-30 13:58:29)_

outdated

**Comment by cstockloew** [comment]
issue cloed on 2015-01-30 13:58:29
