### ISSUE TITLE
[uR-Team] unmarshiling exception for Google-GSon library

### ISSUE THREAD

**Issue by cstockloew** [universAAL/middleware#371]
_Originally Opened: @stefanolenzi-cnr (2013-09-24 17:56:09_)
_Originally Closed: 2014-05-20 16:07:46_

As reported by Andrej and other it seems that the following exception is thrwon from the 2nd instance of uAAL that tries to join to an AAL Space.
Nevertheles, no exception is shown when using the karaf.distro, so it could be a problem of the bundle used.

For replicating the issue please start to version of the runner
http://forge.universaal.org/svn/uaal_ui/sandboxes/eandgrg/uiFw.runner
with the command 
mvn pax:run

mw.container.osgi[org.universAAL.mw.connectors.communication.jgroups.osgi] : JGroupsCommunicationConnector-&gt;receive(): Failed to unmarhall message due to exception java.lang.Exception: Unable to unmashall AALSpaceMessage. Original message: {&quot;channelNames&quot;:[&quot;mw.modules.aalspace.osgi&quot;],&quot;sender&quot;:{&quot;peerID&quot;:&quot;a9fb85d3-a98e-4610-8e25-512e118e58de&quot;,&quot;role&quot;:&quot;PEER&quot;,&quot;PLATFORM_UNIT&quot;:&quot;&quot;,&quot;CONTAINER_UNIT&quot;:&quot;&quot;,&quot;OS&quot;:&quot;Windows Vista - 6.1- x86&quot;},&quot;content&quot;:&quot;{\&quot;aalSpaceMessageType\&quot;:\&quot;JOIN_REQUEST\&quot;,\&quot;spaceDescriptor\&quot;:{\&quot;spaceCard\&quot;:{\&quot;spaceName\&quot;:\&quot;myHome3\&quot;,\&quot;spaceID\&quot;:\&quot;8888\&quot;,\&quot;description\&quot;:\&quot;Super Domestic Home\&quot;,\&quot;peerCoordinatorID\&quot;:\&quot;b49a064d-513e-4680-9610-f06593f4ff32\&quot;,\&quot;peeringChannel\&quot;:\&quot;http://aaloa.isti.cnr.it/udp.xml\&quot;,\&quot;peeringChannelName\&quot;:\&quot;mw.modules.aalspace.osgi\&quot;,\&quot;profile\&quot;:null,\&quot;retry\&quot;:2,\&quot;aalSpaceLifeTime\&quot;:0},\&quot;brokerChannels\&quot;:[],\&quot;deployManager\&quot;:null},\&quot;mtype\&quot;:\&quot;AALSpaceMessage\&quot;}&quot;}. Full Stack: java.lang.RuntimeException: Unable to invoke no-args constructor for class org.universAAL.middleware.connectors.util.ChannelMessage. Register an InstanceCreator with Gson for this type may fix this problem.
      at org.universAAL.middleware.connectors.util.ChannelMessage.unmarshall(ChannelMessage.java:106)
      at org.universAAL.middleware.connectors.communication.jgroups.JGroupsCommunicationConnector.receive(JGroupsCommunicationConnector.java:784)
      at org.jgroups.JChannel.up(JChannel.java:749)
      at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:1017)
      at org.jgroups.stack.Protocol.up(Protocol.java:406)
      at org.jgroups.protocols.RSVP.up(RSVP.java:221)
      at org.jgroups.protocols.FRAG2.up(FRAG2.java:192)
      at org.jgroups.protocols.FlowControl.up(FlowControl.java:461)

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by cstockloew** [comment]
_Original author: @stefanolenzi-cnr (2014-05-20 16:07:14)_

It seems to be related to issue #392 please follow that, I'm marking this as duplicate

**Comment by cstockloew** [comment]
issue cloed on 2014-05-20 16:07:46
