### ISSUE TITLE
Bus Member Tracker is not modular

### ISSUE THREAD

**Issue by Alfiva** [universAAL/middleware#485]
Say you don't have the UI bus installed, because you don't want to use it. The Bus Member Tracker will get a Null pointer exception:

java.lang.NullPointerException
        at org.universAAL.middleware.ui.impl.UIBusImpl.getUIBusFetchParams(UIBusImpl.java:67)
        at org.universAAL.middleware.ui.UIBusFacade.fetchBus(UIBusFacade.java:24)
        at org.universAAL.middleware.tracker.impl.BusMemberRegistryImpl.addUIBusListener(BusMemberRegistryImpl.java:236)
        at org.universAAL.middleware.tracker.impl.BusMemberRegistryImpl.<init>(BusMemberRegistryImpl.java:198)
        at org.universAAL.middleware.tracker.impl.Activator.start(Activator.java:37)

This is because it always registers a UI bus listener (the same happens for other buses) regardless of the presence of that bus. And when it gets to getUIBusFetchParams it fails because it tries to clone the bus fetch params, which are null.

**Comment by amedranogil** [comment]
The case of not all buses being installed was never discussed. 
This discussion may open the door to MW customization (not only buses, but managers and all of it), right now we have the single MW feature to ensure the whole MW is installed

**Comment by Alfiva** [comment]
Could this be fixed now? I do use "Modular" buses in Android: you can choose not to engage the UI bus. And because of that the bus member tracker fails. The tracker is only started when using the Space Gateway for remote communication, though, but that means that right now I cannot use it.
Let me know if this can be fixed today or tomorrow, or else I will implement a workaround in the Android branch of the MW.
Of course in the meantime I can work around this simply by enabling the UI bus in Android.

**Comment by amedranogil** [comment]
I cannot work on it these days, but the fix should be simple to do.

**Comment by Alfiva** [comment]
I think so too, but since I haven't worked in the code, I didn't wan to meddle with it. Anyway, I will enable UI Bus for now, and if I have some time I will try to implement a fix in the Android branch. If that works, I will post it here.

**Comment by amedranogil** [comment]
Please review and test before closing

**Comment by cstockloew** [comment]
I'm not sure if this is really modular (even if it works) because it still has a dependency to UI bus (and the other buses..). From my understanding, this workaround catches the case that the UI Bus module is available, but it is not started (the Activator.start() method is not called).

However, to make it really modular, we should modify it in a way that the UI Bus can be completely missing..

**Comment by amedranogil** [comment]
you're absolutely right.
Maybe in OSGi it is just a matter of setting bus dependency as [optional](http://web.ist.utl.pt/ist162500/?p=65#Optional_Imports). I don't know if that would work for android though.

Another solution might be to move, or register, bus fetch parameters to abstract bus. 
I think in order to truly address this issue we must think of all buses as "addons", think on the possibility of adding a new full fledged semantic bus (e.g: configuration bus) then the bus infrastructure should be automatically be able to adapt. Of course this is tricky, and things like the bustracker (and MTGW) should be radically changed to take full advantage of this concept.

**Comment by amedranogil** [comment]
commit d9856522d1720955cd5b4ac7a1c55d73ca4c5623 might solve the issue in OSGi.
